# importing libraries

In [1]:
import pandas as pd
import json

# loading Data

In [2]:
data = pd.read_csv('dataset_9.csv',header= None)

In [3]:
data

,0,1,2,3,4,5
0,2021-08-26 17:47:13.727000+00:00,2039297081,ARI6,1630000033,"[""number to reach us"",""simply hang up""]",/NAS/airecordings/ARI6-1630000033.0-in.wav
1,2021-10-04 18:05:31.995000+00:00,2032331188,ARI1,1633370731,"[""tone please record your message""]",/NAS/airecordings/ARI1-1633370731.25142-in.wav
2,2021-10-04 18:05:32.218000+00:00,2014372398,ARI1,1633370732,"[""hello""]",/NAS/airecordings/ARI1-1633370732.25144-in.wav
3,2021-10-04 18:05:32.855000+00:00,2564858188,ARI4,1633370732,"[""hello"",""alright"",""i dont have any credit car...",/NAS/airecordings/ARI4-1633370732.23168-in.wav
4,2021-10-04 18:05:34.609000+00:00,5594850953,ARI4,1633370734,"[""hello"",""no i dont""]",/NAS/airecordings/ARI4-1633370734.23173-in.wav
...,...,...,...,...,...,...
99996,2021-10-05 23:22:13.962000+00:00,5615787365,ARI2,1633476134,"[""unavailable please speak clearly your voice ...",/NAS/airecordings/ARI2-1633476133.9205-in.wav
99997,2021-10-05 23:22:14.059000+00:00,9793452649,ARI2,1633476135,"[""hello"",""i dont try""]",/NAS/airecordings/ARI2-1633476134.9209-in.wav
99998,2021-10-05 23:22:14.177000+00:00,7138647121,ARI1,1633476135,"[""at the tone please record your message when ...",/NAS/airecordings/ARI1-1633476134.9389-in.wav
99999,2021-10-05 23:22:14.641000+00:00,7407755560,ARI1,1633476135,"[""i said hello""]",/NAS/airecordings/ARI1-1633476134.9395-in.wav
100000,2021-10-05 23:22:15.171000+00:00,8286893590,ARI1,1633476136,"[""hello"",""hello""]",/NAS/airecordings/ARI1-1633476135.9397-in.wav

# Renaming Columns

In [4]:
data = data.rename({0: 'data.date', 1: 'data.number', 2:'data.application',3:'data.id',4:'data.rawTranscription'}, axis=1)

In [5]:
data.drop(5,axis=1,inplace=True)

In [6]:
data

,data.date,data.number,data.application,data.id,data.rawTranscription
0,2021-08-26 17:47:13.727000+00:00,2039297081,ARI6,1630000033,"[""number to reach us"",""simply hang up""]"
1,2021-10-04 18:05:31.995000+00:00,2032331188,ARI1,1633370731,"[""tone please record your message""]"
2,2021-10-04 18:05:32.218000+00:00,2014372398,ARI1,1633370732,"[""hello""]"
3,2021-10-04 18:05:32.855000+00:00,2564858188,ARI4,1633370732,"[""hello"",""alright"",""i dont have any credit car..."
4,2021-10-04 18:05:34.609000+00:00,5594850953,ARI4,1633370734,"[""hello"",""no i dont""]"
...,...,...,...,...,...
99996,2021-10-05 23:22:13.962000+00:00,5615787365,ARI2,1633476134,"[""unavailable please speak clearly your voice ..."
99997,2021-10-05 23:22:14.059000+00:00,9793452649,ARI2,1633476135,"[""hello"",""i dont try""]"
99998,2021-10-05 23:22:14.177000+00:00,7138647121,ARI1,1633476135,"[""at the tone please record your message when ..."
99999,2021-10-05 23:22:14.641000+00:00,7407755560,ARI1,1633476135,"[""i said hello""]"
100000,2021-10-05 23:22:15.171000+00:00,8286893590,ARI1,1633476136,"[""hello"",""hello""]"

# changing type of rawTranscription

In [7]:
# changing type of rawTranscription
data['data.rawTranscription'] = data['data.rawTranscription'].apply(lambda x : json.loads(x))

In [8]:
data1=data.explode('data.rawTranscription')
data1

,data.date,data.number,data.application,data.id,data.rawTranscription
0,2021-08-26 17:47:13.727000+00:00,2039297081,ARI6,1630000033,number to reach us
0,2021-08-26 17:47:13.727000+00:00,2039297081,ARI6,1630000033,simply hang up
1,2021-10-04 18:05:31.995000+00:00,2032331188,ARI1,1633370731,tone please record your message
2,2021-10-04 18:05:32.218000+00:00,2014372398,ARI1,1633370732,hello
3,2021-10-04 18:05:32.855000+00:00,2564858188,ARI4,1633370732,hello
...,...,...,...,...,...
99997,2021-10-05 23:22:14.059000+00:00,9793452649,ARI2,1633476135,i dont try
99998,2021-10-05 23:22:14.177000+00:00,7138647121,ARI1,1633476135,at the tone please record your message when yo...
99999,2021-10-05 23:22:14.641000+00:00,7407755560,ARI1,1633476135,i said hello
100000,2021-10-05 23:22:15.171000+00:00,8286893590,ARI1,1633476136,hello
100000,2021-10-05 23:22:15.171000+00:00,8286893590,ARI1,1633476136,hello

# audio name

In [10]:
data1['audio_name'] = data1['data.application'] +'-'+ data1['data.id'].astype(str)+'-in.wav'

In [11]:
data1

,data.date,data.number,data.application,data.id,data.rawTranscription,audio_name
0,2021-08-26 17:47:13.727000+00:00,2039297081,ARI6,1630000033,number to reach us,ARI6-1630000033-in.wav
0,2021-08-26 17:47:13.727000+00:00,2039297081,ARI6,1630000033,simply hang up,ARI6-1630000033-in.wav
1,2021-10-04 18:05:31.995000+00:00,2032331188,ARI1,1633370731,tone please record your message,ARI1-1633370731-in.wav
2,2021-10-04 18:05:32.218000+00:00,2014372398,ARI1,1633370732,hello,ARI1-1633370732-in.wav
3,2021-10-04 18:05:32.855000+00:00,2564858188,ARI4,1633370732,hello,ARI4-1633370732-in.wav
...,...,...,...,...,...,...
99997,2021-10-05 23:22:14.059000+00:00,9793452649,ARI2,1633476135,i dont try,ARI2-1633476135-in.wav
99998,2021-10-05 23:22:14.177000+00:00,7138647121,ARI1,1633476135,at the tone please record your message when yo...,ARI1-1633476135-in.wav
99999,2021-10-05 23:22:14.641000+00:00,7407755560,ARI1,1633476135,i said hello,ARI1-1633476135-in.wav
100000,2021-10-05 23:22:15.171000+00:00,8286893590,ARI1,1633476136,hello,ARI1-1633476136-in.wav
100000,2021-10-05 23:22:15.171000+00:00,8286893590,ARI1,1633476136,hello,ARI1-1633476136-in.wav

# chunk name

In [12]:
chunk_name = []
def chunk(x):
    for count,val in enumerate(x):
        chunk_name.append(str(count+1))

In [13]:
data['data.rawTranscription'].apply(chunk)

0         None
1         None
2         None
3         None
4         None
          ...
99996     None
99997     None
99998     None
99999     None
100000    None
Name: data.rawTranscription, Length: 100001, dtype: object

In [14]:
chunk_name[0:10]

['1', '2', '1', '1', '1', '2', '3', '1', '2', '1']

In [15]:
data1['chunk_name'] =  data1['data.application'] +'-'+ data1['data.id'].astype(str)+'-in-' + chunk_name + '.wav'

In [16]:
data1.reset_index(drop=True)

,data.date,data.number,data.application,data.id,data.rawTranscription,audio_name,chunk_name
0,2021-08-26 17:47:13.727000+00:00,2039297081,ARI6,1630000033,number to reach us,ARI6-1630000033-in.wav,ARI6-1630000033-in-1.wav
1,2021-08-26 17:47:13.727000+00:00,2039297081,ARI6,1630000033,simply hang up,ARI6-1630000033-in.wav,ARI6-1630000033-in-2.wav
2,2021-10-04 18:05:31.995000+00:00,2032331188,ARI1,1633370731,tone please record your message,ARI1-1633370731-in.wav,ARI1-1633370731-in-1.wav
3,2021-10-04 18:05:32.218000+00:00,2014372398,ARI1,1633370732,hello,ARI1-1633370732-in.wav,ARI1-1633370732-in-1.wav
4,2021-10-04 18:05:32.855000+00:00,2564858188,ARI4,1633370732,hello,ARI4-1633370732-in.wav,ARI4-1633370732-in-1.wav
...,...,...,...,...,...,...,...
195015,2021-10-05 23:22:14.059000+00:00,9793452649,ARI2,1633476135,i dont try,ARI2-1633476135-in.wav,ARI2-1633476135-in-2.wav
195016,2021-10-05 23:22:14.177000+00:00,7138647121,ARI1,1633476135,at the tone please record your message when yo...,ARI1-1633476135-in.wav,ARI1-1633476135-in-1.wav
195017,2021-10-05 23:22:14.641000+00:00,7407755560,ARI1,1633476135,i said hello,ARI1-1633476135-in.wav,ARI1-1633476135-in-1.wav
195018,2021-10-05 23:22:15.171000+00:00,8286893590,ARI1,1633476136,hello,ARI1-1633476136-in.wav,ARI1-1633476136-in-1.wav
195019,2021-10-05 23:22:15.171000+00:00,8286893590,ARI1,1633476136,hello,ARI1-1633476136-in.wav,ARI1-1633476136-in-2.wav