In [158]:
import pandas as pd

In [ ]:
df_cdr = pd.read_csv(r"Z:\AIDAILER\cdr\cdr.csv",warn_bad_lines=True, error_bad_lines=False, engine="python")

C:\Users\trainee10\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: FutureWarning: The warn_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)
C:\Users\trainee10\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)

In [160]:
df_cdr.columns

Index(['id', 'callid', 'callid_b', 'switch', 'call_time', 'source_ip',
       'source_number', 'account_id', 'account_card_id', 'reseller_id',
       'dest_cli', 'tech_prefix', 'dest_number', 'lrn_number', 'jurisdiction',
       'customer_dest_code', 'reseller_dest_code', 'provider_dest_code',
       'customer_dest_name', 'reseller_dest_name', 'provider_dest_name',
       'customer_duration', 'reseller_duration', 'provider_duration',
       'customer_rate', 'reseller_rate', 'provider_rate', 'duration',
       'customer_mcd', 'customer_pulse', 'customer_connect_cost',
       'reseller_mcd', 'reseller_pulse', 'reseller_connect_cost',
       'provider_mcd', 'provider_pulse', 'provider_connect_cost',
       'release_reason', 'pdd_in', 'pdd_out', 'ring_duration', 'provider_id',
       'provider_card_id', 'cost', 'retail', 'reseller', 'cost_currency',
       'retail_currency', 'reseller_currency', 'status', 'from_tag', 'to_tag',
       'sip_code', 'sip_reason', 'dtmf', 'ingress_id', 'recording_cost',
       'billing_id', 'failed_routes', 'rtp_info'],
      dtype='object')

In [161]:
pd.set_option('max_columns', None)

In [162]:
df_cdr.head()

,id,callid,callid_b,switch,call_time,source_ip,source_number,account_id,account_card_id,reseller_id,dest_cli,tech_prefix,dest_number,lrn_number,jurisdiction,customer_dest_code,reseller_dest_code,provider_dest_code,customer_dest_name,reseller_dest_name,provider_dest_name,customer_duration,reseller_duration,provider_duration,customer_rate,reseller_rate,provider_rate,duration,customer_mcd,customer_pulse,customer_connect_cost,reseller_mcd,reseller_pulse,reseller_connect_cost,provider_mcd,provider_pulse,provider_connect_cost,release_reason,pdd_in,pdd_out,ring_duration,provider_id,provider_card_id,cost,retail,reseller,cost_currency,retail_currency,reseller_currency,status,from_tag,to_tag,sip_code,sip_reason,dtmf,ingress_id,recording_cost,billing_id,failed_routes,rtp_info
0,573149379,278c0f951a5815325bc7d46256f37594@148.72.173.23...,CNX2920_cQdWLQM+ZgcIUwVnchFwAlssUG87Bg8ABWklF3...,159.203.92.196,Mon Jan 18 2021 19:00:00 GMT+0000 (Coordinated...,148.72.173.23,9736359882,71965,vULt-YDs3,NaN,9736359882,NaN,19736352534,1.732641e+10,NaN,1732640,NaN,1732640,NaN,NaN,NaN,18,NaN,18,0.002952,NaN,0.002484,15.22,6,6,0,NaN,NaN,NaN,6,6,0,Upstream BYE,2521,2179,7,71083,3zEb-jDz9,0.0007,0.0009,NaN,USD,USD,NaN,Complete,as111680c6,rUtjv9DU4DpKm,200,OK,NaN,100015,NaN,NaN,NaN,NaN
1,573149463,5b1930cb7140168b6d028df8247512cc@148.72.168.22...,CNX3067_dlJfdwBoPFEHBwNvchJ7UlgqA2pnV1YOBWt0EX...,161.35.121.80,Mon Jan 18 2021 19:00:00 GMT+0000 (Coordinated...,148.72.168.228,2516617698,71965,vULt-YDs3,NaN,2516617698,NaN,12516617565,NaN,NaN,1251661,NaN,1251661,NaN,NaN,NaN,0,NaN,0,0.002400,NaN,0.001946,NaN,6,6,0,NaN,NaN,NaN,6,6,0,Unknown,3133,2935,22,70831,FFUw-N2ry,0.0000,0.0000,NaN,USD,USD,NaN,Complete,as51d85d8a,B621eBQa6a8DQ,487,Request Terminated,NaN,100015,NaN,NaN,NaN,NaN
2,573149465,07e8922e77d9338a7a90ba1959eb0214@148.72.168.22...,CNX3067_cwcLdgpqbVYHAVNmcBd7UVkvCmg9UgEPAmYmRn...,161.35.121.80,Mon Jan 18 2021 19:00:00 GMT+0000 (Coordinated...,148.72.168.228,7702529396,71965,vULt-YDs3,NaN,7702529396,NaN,17702528291,1.678765e+10,NaN,1678765,NaN,1678765,NaN,NaN,NaN,0,NaN,0,0.006500,NaN,0.004906,NaN,6,6,0,NaN,NaN,NaN,6,6,0,Unknown,3439,3205,0,71083,3zEb-jDz9,0.0000,0.0000,NaN,USD,USD,NaN,Complete,as7af79676,DX8tUvDr9S8jr,500,Service Unavailable,NaN,100015,NaN,NaN,NaN,NaN
3,573149639,15e10157538188f0171ef57c1f4a1667@148.72.168.22...,CNX3067_cgULfwNpagQFBQ9uexwlAF95Aj05BgdVBjl3RX...,161.35.121.80,Mon Jan 18 2021 19:00:00 GMT+0000 (Coordinated...,148.72.168.228,7706276068,71965,vULt-YDs3,NaN,7706276068,NaN,17706274181,1.770926e+10,NaN,1770926,NaN,1770926,NaN,NaN,NaN,0,NaN,0,0.002420,NaN,0.001978,NaN,6,6,0,NaN,NaN,NaN,6,6,0,Unknown,1858,1671,23,70831,FFUw-N2ry,0.0000,0.0000,NaN,USD,USD,NaN,Complete,as530f7139,5y0ZBQZDg2BDr,487,Request Terminated,NaN,100015,NaN,NaN,NaN,NaN
4,573149641,07e8922e77d9338a7a90ba1959eb0214@148.72.168.22...,CNX3067_cwcLdgpqbVYHAVNmcBd7UVkvCmg9UgEPAmYmRn...,161.35.121.80,Mon Jan 18 2021 19:00:00 GMT+0000 (Coordinated...,148.72.168.228,7702529396,71965,vULt-YDs3,NaN,7702529396,NaN,17702528291,1.678765e+10,NaN,1678765,NaN,1678765,NaN,NaN,NaN,0,NaN,0,0.006500,NaN,0.006452,NaN,6,6,0,NaN,NaN,NaN,6,6,0,Unknown,3439,3205,0,70831,FFUw-N2ry,0.0000,0.0000,NaN,USD,USD,NaN,Complete,as7af79676,5da0-a85fcb36f6bb5e06de05e9e77b6429b0,500,Service Unavailable,NaN,100015,NaN,NaN,NaN,NaN

In [187]:
# formatted_df = df_cdr['call_time'].dt.strftime('%m/%d/%y')
a = list(dfnew['call_time'])

In [246]:
list1 = dfnew['call_time'].to_list()

# dfnew['call_time'][0][3:25]
date_time =  [i[3:25] for i in list1]

In [260]:
dfnew[dfnew['call_time'].str.contains(' Feb ')]

Empty DataFrame
Columns: [id, callid, callid_b, switch, call_time, source_ip, source_number, account_id, account_card_id, reseller_id, dest_cli, tech_prefix, dest_number, lrn_number, jurisdiction, customer_dest_code, reseller_dest_code, provider_dest_code, customer_dest_name, reseller_dest_name, provider_dest_name, customer_duration, reseller_duration, provider_duration, customer_rate, reseller_rate, provider_rate, duration, customer_mcd, customer_pulse, customer_connect_cost, reseller_mcd, reseller_pulse, reseller_connect_cost, provider_mcd, provider_pulse, provider_connect_cost, release_reason, pdd_in, pdd_out, ring_duration, provider_id, provider_card_id, cost, retail, reseller, cost_currency, retail_currency, reseller_currency, status, from_tag, to_tag, sip_code, sip_reason, dtmf, ingress_id, recording_cost, billing_id, failed_routes, rtp_info]
Index: []

In [262]:
dfnew['call_time'] = date_time

In [285]:
d = {'Jan':1,}

In [292]:
d["Jan"]

1

In [286]:
newdf.call_time = newdf.call_time.map(d)

In [291]:
df_cdr['call_time']

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
          ..
947278   NaN
947279   NaN
947280   NaN
947281   NaN
947282   NaN
Name: call_time, Length: 947283, dtype: float64

In [271]:
dfnew1['call_time']

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
          ..
947278   NaN
947279   NaN
947280   NaN
947281   NaN
947282   NaN
Name: call_time, Length: 947283, dtype: float64

In [274]:
df_cdr['call_time']

0         Mon Jan 18 2021 19:00:00 GMT+0000 (Coordinated...
1         Mon Jan 18 2021 19:00:00 GMT+0000 (Coordinated...
2         Mon Jan 18 2021 19:00:00 GMT+0000 (Coordinated...
3         Mon Jan 18 2021 19:00:00 GMT+0000 (Coordinated...
4         Mon Jan 18 2021 19:00:00 GMT+0000 (Coordinated...
                                ...
947278    Wed Jan 20 2021 15:50:56 GMT+0000 (Coordinated...
947279    Wed Jan 20 2021 15:50:56 GMT+0000 (Coordinated...
947280    Wed Jan 20 2021 15:50:56 GMT+0000 (Coordinated...
947281    Wed Jan 20 2021 15:50:57 GMT+0000 (Coordinated...
947282    Wed Jan 20 2021 15:50:58 GMT+0000 (Coordinated...
Name: call_time, Length: 947283, dtype: object

In [277]:
 newdf = df_cdr

In [278]:
newdf.head()

,id,callid,callid_b,switch,call_time,source_ip,source_number,account_id,account_card_id,reseller_id,dest_cli,tech_prefix,dest_number,lrn_number,jurisdiction,customer_dest_code,reseller_dest_code,provider_dest_code,customer_dest_name,reseller_dest_name,provider_dest_name,customer_duration,reseller_duration,provider_duration,customer_rate,reseller_rate,provider_rate,duration,customer_mcd,customer_pulse,customer_connect_cost,reseller_mcd,reseller_pulse,reseller_connect_cost,provider_mcd,provider_pulse,provider_connect_cost,release_reason,pdd_in,pdd_out,ring_duration,provider_id,provider_card_id,cost,retail,reseller,cost_currency,retail_currency,reseller_currency,status,from_tag,to_tag,sip_code,sip_reason,dtmf,ingress_id,recording_cost,billing_id,failed_routes,rtp_info
0,573149379,278c0f951a5815325bc7d46256f37594@148.72.173.23...,CNX2920_cQdWLQM+ZgcIUwVnchFwAlssUG87Bg8ABWklF3...,159.203.92.196,Mon Jan 18 2021 19:00:00 GMT+0000 (Coordinated...,148.72.173.23,9736359882,71965,vULt-YDs3,NaN,9736359882,NaN,19736352534,1.732641e+10,NaN,1732640,NaN,1732640,NaN,NaN,NaN,18,NaN,18,0.002952,NaN,0.002484,15.22,6,6,0,NaN,NaN,NaN,6,6,0,Upstream BYE,2521,2179,7,71083,3zEb-jDz9,0.0007,0.0009,NaN,USD,USD,NaN,Complete,as111680c6,rUtjv9DU4DpKm,200,OK,NaN,100015,NaN,NaN,NaN,NaN
1,573149463,5b1930cb7140168b6d028df8247512cc@148.72.168.22...,CNX3067_dlJfdwBoPFEHBwNvchJ7UlgqA2pnV1YOBWt0EX...,161.35.121.80,Mon Jan 18 2021 19:00:00 GMT+0000 (Coordinated...,148.72.168.228,2516617698,71965,vULt-YDs3,NaN,2516617698,NaN,12516617565,NaN,NaN,1251661,NaN,1251661,NaN,NaN,NaN,0,NaN,0,0.002400,NaN,0.001946,NaN,6,6,0,NaN,NaN,NaN,6,6,0,Unknown,3133,2935,22,70831,FFUw-N2ry,0.0000,0.0000,NaN,USD,USD,NaN,Complete,as51d85d8a,B621eBQa6a8DQ,487,Request Terminated,NaN,100015,NaN,NaN,NaN,NaN
2,573149465,07e8922e77d9338a7a90ba1959eb0214@148.72.168.22...,CNX3067_cwcLdgpqbVYHAVNmcBd7UVkvCmg9UgEPAmYmRn...,161.35.121.80,Mon Jan 18 2021 19:00:00 GMT+0000 (Coordinated...,148.72.168.228,7702529396,71965,vULt-YDs3,NaN,7702529396,NaN,17702528291,1.678765e+10,NaN,1678765,NaN,1678765,NaN,NaN,NaN,0,NaN,0,0.006500,NaN,0.004906,NaN,6,6,0,NaN,NaN,NaN,6,6,0,Unknown,3439,3205,0,71083,3zEb-jDz9,0.0000,0.0000,NaN,USD,USD,NaN,Complete,as7af79676,DX8tUvDr9S8jr,500,Service Unavailable,NaN,100015,NaN,NaN,NaN,NaN
3,573149639,15e10157538188f0171ef57c1f4a1667@148.72.168.22...,CNX3067_cgULfwNpagQFBQ9uexwlAF95Aj05BgdVBjl3RX...,161.35.121.80,Mon Jan 18 2021 19:00:00 GMT+0000 (Coordinated...,148.72.168.228,7706276068,71965,vULt-YDs3,NaN,7706276068,NaN,17706274181,1.770926e+10,NaN,1770926,NaN,1770926,NaN,NaN,NaN,0,NaN,0,0.002420,NaN,0.001978,NaN,6,6,0,NaN,NaN,NaN,6,6,0,Unknown,1858,1671,23,70831,FFUw-N2ry,0.0000,0.0000,NaN,USD,USD,NaN,Complete,as530f7139,5y0ZBQZDg2BDr,487,Request Terminated,NaN,100015,NaN,NaN,NaN,NaN
4,573149641,07e8922e77d9338a7a90ba1959eb0214@148.72.168.22...,CNX3067_cwcLdgpqbVYHAVNmcBd7UVkvCmg9UgEPAmYmRn...,161.35.121.80,Mon Jan 18 2021 19:00:00 GMT+0000 (Coordinated...,148.72.168.228,7702529396,71965,vULt-YDs3,NaN,7702529396,NaN,17702528291,1.678765e+10,NaN,1678765,NaN,1678765,NaN,NaN,NaN,0,NaN,0,0.006500,NaN,0.006452,NaN,6,6,0,NaN,NaN,NaN,6,6,0,Unknown,3439,3205,0,70831,FFUw-N2ry,0.0000,0.0000,NaN,USD,USD,NaN,Complete,as7af79676,5da0-a85fcb36f6bb5e06de05e9e77b6429b0,500,Service Unavailable,NaN,100015,NaN,NaN,NaN,NaN

In [245]:
data[] = date_time

[' Jan 18 2021 19:00:00 ',
 ' Jan 18 2021 19:00:00 ',
 ' Jan 18 2021 19:00:00 ',
 ' Jan 18 2021 19:00:00 ',
 ' Jan 18 2021 19:00:00 ']

In [218]:
date_format=[]
for i in a:
    i.remove(' GMT+0000 (Coordinated Universal Time)')
    date_format.append(i)

AttributeError: 'str' object has no attribute 'remove'

In [240]:
dfnew['call_time'][0][3:25]

' Jan 18 2021 19:00:00 '

In [195]:
dfnew['call_time'] =

0         Mon Jan 18 2021 19:00:00 GMT+0000 (Coordinated...
1         Mon Jan 18 2021 19:00:00 GMT+0000 (Coordinated...
2         Mon Jan 18 2021 19:00:00 GMT+0000 (Coordinated...
3         Mon Jan 18 2021 19:00:00 GMT+0000 (Coordinated...
4         Mon Jan 18 2021 19:00:00 GMT+0000 (Coordinated...
                                ...
947278    Wed Jan 20 2021 15:50:56 GMT+0000 (Coordinated...
947279    Wed Jan 20 2021 15:50:56 GMT+0000 (Coordinated...
947280    Wed Jan 20 2021 15:50:56 GMT+0000 (Coordinated...
947281    Wed Jan 20 2021 15:50:57 GMT+0000 (Coordinated...
947282    Wed Jan 20 2021 15:50:58 GMT+0000 (Coordinated...
Name: call_time, Length: 947283, dtype: object

In [194]:
a.remove([1][0:3])

ValueError: list.remove(x): x not in list

In [157]:
df_cdr['call_time']

0        NaT
1        NaT
2        NaT
3        NaT
4        NaT
          ..
947278   NaT
947279   NaT
947280   NaT
947281   NaT
947282   NaT
Name: call_time, Length: 947283, dtype: datetime64[ns]

In [217]:
dfnew['call_time'] = pd.to_datetime(dfnew['call_time']).dt.strftime('%H:%M')
dfnew

ParserError: Unknown string format: Mon Jan 18 2021 19:00:00 GMT+0000 (Coordinated Universal Time)

In [ ]:
localtime =dfnew['call_time'].to_list()
hr = [str(t).split(":")[0].split()[-1] for t in localtime]

In [147]:
# df_cdr['call_time'] = pd.to_datetime(df_cdr["call_time"].dt.strftime('%Y-%m'))
df_cdr['call_time']=pd.to_datetime(df_cdr['call_time'].astype(str), format='%m/%d/%Y %H:%M:%S.%f')

ValueError: time data 'Mon Jan 18 2021 19:00:00 GMT+0000 (Coordinated Universal Time)' does not match format '%m/%d/%Y %H:%M:%S.%f' (match)

In [90]:
type(df_cdr['date'][0])

str

In [91]:
df_cdr['date'].value_counts()

2021-01-02 19:33:44    68
2021-01-02 18:45:22    68
2021-01-02 16:08:57    66
2021-01-02 18:53:06    64
2021-01-02 19:29:28    63
                       ..
2021-01-02 15:41:23     1
2021-01-02 16:27:25     1
2021-01-02 17:00:03     1
2021-01-02 19:53:13     1
2021-01-02 20:24:00     1
Name: date, Length: 15857, dtype: int64

In [92]:
df_cdr['date'].unique()

array(['2021-01-02 15:04:58', '2021-01-02 15:04:59',
       '2021-01-02 15:05:00', ..., '2021-01-02 20:20:05',
       '2021-01-02 20:20:00', '2021-01-02 20:24:00'], dtype=object)

In [93]:
df_cdr['date'].isnull().value_counts()

False    480548
Name: date, dtype: int64

In [94]:
type(df_cdr['duration'][10])

numpy.int64

In [95]:
df_cdr['duration'].unique()

array([   0,   29,   33,   34,    5,    3,   16,   42,   30,  116,   28,
         18,   35,   20,   26,    6,   31,    4,    8,   10,    7,   27,
         14,   25,   22,   39,    1,   11,    2,    9,   21,   17,   23,
         41,   13,   32,   24,   19,   15,   36,   50,   43,   57,  122,
         12,  358,  141,   40,   72,  102,   49,   95,   62,  107,   48,
         71,   91,   55,   78,   59,   65,   75,   51,   37,   56,   98,
         81,  270,   73,   97,   70,   85,   38,  345,  120,  382,   83,
         54,  197,   61,   80,  206,   64,  119,   99,   58,   86,  105,
         44,   63,   52,   53,   68,  121,   67,  175,  301,  100,   45,
         66,  232,   60,   84,   76,   92,  304,  115,   79,  182, 4055,
         46,  329,   69,   74,  131,  400,  118,   89,  113,  133,   47,
         82,  194,   90,   87,  103,  158,  149,  239,   93,   77,  110,
        114,  112,  221,  111,   96,  299,  166,  129,  117,  125,  126,
        146,  271,  171, 3035,  104,  233,  366,  128,  211,  124,  132,
        148,  157,  101,  806,  268,  150,  290,  142,  108,   88,  247,
        184,  159,  181,  138, 2747,  238,  127,  185,  135,  272,  749,
        192, 2398,  332,  792,  167,  234,  143,  351,  320,  658,  160,
        169,  106,  227,  236,  186,  462,  156,  155,  277,  347,  518,
        109,  226,  161,  137,  373,   94,  189,  424,  172,  134,  281,
        269,  151,  265,  223,  123,  788,  333,  252,  362,  170,  178,
       1601,  310,  173, 2245,  195,  218,  340,  152,  136,  191,  193,
        337,  210,  327,  130,  242,  798,  208,  139,  163,  214,  971,
        317,  240,  267,  284,  209,  176,  244,  164,  572,  425,  225,
        190,  203,  371,  204,  187,  934,  140,  180,  292,  353,  280,
        144, 4002,  145,  162,  263,  554,  318,  331,  521, 1653,  291,
        228,  397,  389], dtype=int64)

In [96]:
df_cdr['duration'].value_counts()

0      325749
3       52114
4       17134
5        8333
35       4784
        ...
373         1
206         1
382         1
518         1
389         1
Name: duration, Length: 278, dtype: int64

In [99]:
df_cdr['dst_number'].value_counts()

9105721200    4
8069353220    4
6105321791    4
7604801227    3
7188495706    3
             ..
5616993636    1
8282732260    1
7725621180    1
8056844042    1
4016352845    1
Name: dst_number, Length: 479591, dtype: int64

In [101]:
df_cdr['dst_number'].unique()

array([9788367424, 6316652128, 9736973406, ..., 3609785233, 4017622411,
       4016352845], dtype=int64)

In [103]:
type(df_cdr['dst_number'][0])

numpy.int64

In [141]:
df_cdr1 = pd.read_csv(r"Z:\AIDAILER\cdr\2021-06-30.csv",warn_bad_lines=True, error_bad_lines=False, engine="python")

C:\Users\trainee10\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: FutureWarning: The warn_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)
C:\Users\trainee10\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)

In [142]:
df_cdr1.head()

,date,src_number,dst_number,billed_number,duration,account_id,src_ip,account_jurisdiction,account_billed_duration,account_rate,account_cost,callid,lrn_number
0,2021-06-30 14:39:29,8003741625,8003742683,800374,34,38,148.72.171.85,Indet,34,0.000000,0.0000,3cdf407f5bc660db5abca4f300887148@148.72.171.85...,8003742683
1,2021-06-30 14:42:20,8666009556,9786862257,978304,15,38,148.72.171.85,Indet,15,0.001963,0.0005,071b989e1982b6b9717c2401609b7a23@148.72.171.85...,9783040975
2,2021-06-30 14:46:15,9786861929,9786862257,978304,18,38,148.72.171.85,Intra,18,0.001950,0.0006,16559ceb3cf9dbfb2408723d0be75893@148.72.171.85...,9783040975
3,2021-06-30 14:47:01,9783126091,9783123318,617603,0,38,148.72.171.85,Intra,0,0.002332,0.0000,6af900f43e8568e902cea5ef6866ed04@148.72.171.85...,6176039999
4,2021-06-30 14:47:07,2088528163,2088520895,208852,46,38,148.72.171.85,Intra,46,0.001900,0.0015,47370c9e38951772116225027a182455@148.72.171.85...,2088520895

In [269]:
dfnew1 = df_cdr